
openapi: 3.0.3
info:
  title: Call AI API Documentation
  description: API documentation for integrating Call AI features.
  version: 1.0.0
servers:
  - url: https://api.call-ai.com
    description: Production Server
paths:
  /api/call-ai/v1/meeting/get-transcript/{id}:
    get:
      summary: Retrieve a Transcript
      description: Retrieves the transcript of a specific call.
      parameters:
        - name: id
          in: path
          required: true
          description: Unique identifier for the meeting.
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  meeting_id:
                    type: string
                  transcript:
                    type: array
                    items:
                      type: object
                      properties:
                        speaker:
                          type: string
                        timestamp:
                          type: string
                        text:
                          type: string
        '404':
          description: Transcript not found.
        '403':
          description: Unauthorized access.
        '500':
          description: Internal server error.
  /api/call-ai/v1/meeting/share-transcript:
    post:
      summary: Share a Transcript
      description: Shares a call transcript with another user or team.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                meeting_id:
                  type: string
                recipient_email:
                  type: string
                message:
                  type: string
      responses:
        '200':
          description: Success
        '400':
          description: Invalid request payload.
        '403':
          description: Unauthorized.
        '500':
          description: Internal server error.
